<?php

/**
 * @file
 * Contains imagex_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use League\Csv\Reader;
use Drupal\imagex_custom\Entity\Customer;

/**
 * Implements hook_help().
 */
function imagex_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the imagex_custom module.
    case 'help.page.imagex_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('&#039;&#039;') . '</p>';
      return $output;

    default:
  }
}

function imagex_custom_cron() {
  _imagex_custom_import_customers();
}

function _imagex_custom_import_customers() {
  $next_run = \Drupal::state()
    ->get('imagex_custom.cron_import_customers', 0);
  $current_time = time();

  if ($current_time > $next_run) {
    $csv = Reader::createFromPath('../customers/customers.csv', 'r');
    $csv->setHeaderOffset(0);
    $rows = $csv->getRecords(); //returns all the CSV records as an Iterator object
    foreach ($rows as $row) {
      $id = \Drupal::entityQuery('customer')
        ->condition('customer_name', $row['NAME'])
        ->execute();
      $customer = Customer::load(current($id));
      if (!isset($customer)) {
        $customer = Customer::create();
      }
      $customer->setName($row['NAME']);
      $customer->setBalance($row['BALANCE']);
      $customer->save();
    }

    $next_run = strtotime('+1 hour');
    \Drupal::state()
      ->set('imagex_custom.cron_import_customers', $next_run);
  }
}