<?php

/**
 * @file
 * Contains imagex_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function imagex_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the imagex_custom module.
    case 'help.page.imagex_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('&#039;&#039;') . '</p>';
      return $output;

    default:
  }
}
